services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mandau-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - GO_ENV=production
      - GO_API_URL=http://127.0.0.1:8080
      - PUBLIC_API_URL=/api/v1
