root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api-mandau.exe ."
  entrypoint = "./tmp/api-mandau.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 1000
  send_interrupt = false
  kill_delay = "2s"
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true